all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    db:
      hosts:
        localhost:
    backend:
      hosts:
        localhost:
    frontend:
      hosts:
        localhost:
