- name: Run Nginx container
  docker_container:
    name: frontend
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "{{ frontend_port }}:80"
    networks:
      - name: webstack
    volumes:
      - "{{ role_path }}/templates/nginx.conf.j2:/etc/nginx/conf.d/default.conf:ro"
