- name: Update apt packages
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Docker
  apt:
    name: docker.io
    state: present
  when: ansible_os_family == "Debian"
